import { parseBlogFrontmatter, serializeBlogPost } from '@/lib/blog-frontmatter'
import type { ContentItem, ContentQualityCheck, ContentSource } from '@/lib/content-studio/types'

const SLUG_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/

export interface PublicationPaths {
  branch: string
  markdownPath: string
  imagePath: string
  publicImagePath: string
}

export function assertPublishableSlug(slug: string): void {
  if (!SLUG_PATTERN.test(slug) || slug.length > 120) {
    throw new Error('The article slug is not safe to publish')
  }
}

export function getPublicationPaths(item: Pick<ContentItem, 'id' | 'slug' | 'created_at'>): PublicationPaths {
  assertPublishableSlug(item.slug)
  if (!/^[0-9a-f]{8}-[0-9a-f-]{27}$/i.test(item.id)) throw new Error('The content item ID is invalid')
  const createdDay = item.created_at.slice(0, 10)
  if (!/^\d{4}-\d{2}-\d{2}$/.test(createdDay)) throw new Error('The content creation date is invalid')
  return {
    branch: `content/${createdDay}-${item.slug}-${item.id.slice(0, 8)}`,
    markdownPath: `content/blog/${item.slug}.md`,
    imagePath: `public/blog/${item.slug}.webp`,
    publicImagePath: `/blog/${item.slug}.webp`,
  }
}

export function publicationDateFromExisting(raw: string): string {
  const { data } = parseBlogFrontmatter(raw)
  const date = data.date
  if (!date || !/^\d{4}-\d{2}-\d{2}$/.test(date)) {
    throw new Error('The existing article on the base branch has no valid publication date')
  }
  return date
}

export function serializePublicationMarkdown(
  item: ContentItem,
  publicationDate: string,
  today: string,
): string {
  const paths = getPublicationPaths(item)
  return serializeBlogPost({
    title: item.title,
    description: item.description,
    date: publicationDate,
    updated: item.mode === 'refresh' && today > publicationDate ? today : undefined,
    topic: item.topic,
    author: 'Eimantas Kudarauskas',
    image: paths.publicImagePath,
    related: item.related_slugs.join(', '),
  }, item.markdown)
}

export function buildPullRequestBody(
  item: ContentItem,
  sources: ContentSource[],
  checks: ContentQualityCheck[],
): string {
  const sourceLines = sources.slice(0, 20).map((source) => `- [${source.title || source.publisher || source.url}](${source.url})`)
  const checkLines = checks.map((check) => `- [${check.passed ? 'x' : ' '}] ${check.label} — ${check.detail}`)
  return `## Content Studio publication

This is a review-only draft pull request created from the Owner portal. Merging remains a manual GitHub decision.

### Article brief

- **Mode:** ${item.mode === 'refresh' ? `Refresh \`${item.refresh_slug}\`` : 'New article'}
- **Target query:** ${item.target_query}
- **Search intent:** ${item.search_intent}
- **Reader outcome:** ${item.reader_job}

### Deterministic checks

${checkLines.join('\n')}

### Saved research provenance

${sourceLines.join('\n') || '- No saved research sources'}

### Human review checklist

- [ ] Claims are supported by the linked sources
- [ ] Product capabilities and limitations are accurate
- [ ] Article copy, links, and cover image are approved
- [ ] Vercel preview and repository blog audit pass

_Generated by Loqara Content Studio. No auto-merge or direct production write was requested._`
}
